name: gcw_server
description: GC Wizard API
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.0
  gc_wizard:
    path: ./../

dependency_overrides:
  meta: ^1.15.0


